export enum UserRole {
  PASSENGER = 'PASSENGER',
  DRIVER = 'DRIVER',
  ADMIN = 'ADMIN',
  SUPERADMIN = 'SUPERADMIN',
  SUPER = 'SUPER',
  OPERATIONS = 'OPERATIONS',
  SECURITY = 'SECURITY',
  SUPPORT = 'SUPPORT',
  FINANCE = 'FINANCE',
}
